name: Pull Request Workflow

#CI will be run for PRs when opened, reopened or new commits.
on:
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: |
          if [ ! -f .env ]; then
            cp .env.testing .env
            cp .env.testing .env.testing
          fi

      - name: Install dependencies
        run: make action-install

      - name: Generate key
        run: make key-generate

      - name: Set up app
        run: make up

      - name: Run migrations
        run: make migrate-fresh-testing

      - name: Run tests
        run: make test
