name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env'); copy('.env.testing', '.env.testing');"

      - name: Install dependencies
        run: make action-install

      - name: Generate key
        run: make key-generate

      - name: Set up app
        run: make up

      - name: Run migrations
        run: make migrate-fresh-testing

      - name: Run tests
        run: make test
